#!/usr/bin/env python3
"""Build a legacy case figure from Endpoint+Active rollout model outputs.

The figure intentionally combines two different outputs:

1. Deterministic graph rollout: observed T0 graph, predicted T3 graph, observed
   T3 graph. The predicted graph is generated by the Endpoint+Active fold checkpoint.
2. Conditional MC distribution: the saved T0-to-T3 FTV samples for the same
   patient and Endpoint+Active model.

This keeps the qualitative panel faithful to the model while preserving the
uncertainty histogram that explains the probabilistic forecast.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.colors import LogNorm
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
NB_ISPY2 = ROOT / "notebooks"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))
if str(NB_ISPY2) not in sys.path:
    sys.path.insert(0, str(NB_ISPY2))

import consistent_twin_lib as lib  # noqa: E402


VISIT_TO_IDX = {"T0": 0, "T1": 1, "T2": 2, "T3": 3}
VOLUME_IDX = 1


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
        if bold
        else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/Supplemental/Helvetica.ttc",
        "/Library/Fonts/Arial Bold.ttf" if bold else "/Library/Fonts/Arial.ttf",
    ]
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size=size)
        except Exception:
            pass
    return ImageFont.load_default()


FONTS = {
    "title": font(30, True),
    "subtitle": font(16),
    "row": font(20, True),
    "panel": font(16, True),
    "visit": font(12, True),
    "small": font(12),
    "metric": font(15, True),
    "legend": font(13),
}

COLORS = {
    "navy": "#111827",
    "muted": "#52617a",
    "line": "#cbd5e1",
    "blue": "#1d4ed8",
    "green": "#047857",
    "red": "#dc2626",
    "purple": "#7c3aed",
    "teal": "#0f766e",
    "slate": "#334155",
}


def fig_to_image(fig: plt.Figure) -> Image.Image:
    canvas = FigureCanvas(fig)
    canvas.draw()
    arr = np.asarray(canvas.buffer_rgba())
    return Image.fromarray(arr[:, :, :3].copy())


def knn_edges(points: np.ndarray, k: int = 4) -> list[tuple[int, int]]:
    n = int(points.shape[0])
    if n < 2:
        return []
    d = np.linalg.norm(points[:, None, :] - points[None, :, :], axis=-1)
    np.fill_diagonal(d, np.inf)
    kk = min(k, n - 1)
    idx = np.argpartition(d, kk, axis=1)[:, :kk]
    edges: set[tuple[int, int]] = set()
    for i in range(n):
        for j in idx[i]:
            a, b = sorted((int(i), int(j)))
            edges.add((a, b))
    return sorted(edges)


def node_sizes(volume_ml: np.ndarray) -> np.ndarray:
    volume_ml = np.asarray(volume_ml, dtype=float)
    if volume_ml.size == 0:
        return volume_ml
    vmax = max(float(np.nanpercentile(volume_ml, 95)), 1e-4)
    scaled = np.sqrt(np.clip(volume_ml, 0.0, None) / vmax)
    return 14.0 + 38.0 * np.clip(scaled, 0.0, 1.35)


def draw_viridis_scale(draw: ImageDraw.ImageDraw, x: int, y: int, width: int = 96, height: int = 10) -> None:
    cmap = plt.get_cmap("viridis")
    for i in range(width):
        rgb = tuple(int(255 * v) for v in cmap(i / max(width - 1, 1))[:3])
        draw.line((x + i, y, x + i, y + height), fill=rgb, width=1)
    draw.rectangle((x, y, x + width, y + height), outline="#94a3b8", width=1)


def graph_card(
    *,
    title: str,
    visit_label: str,
    points: np.ndarray,
    volumes_ml: np.ndarray,
    row_norm: LogNorm,
    card_size: tuple[int, int] = (250, 220),
    badge_color: str,
) -> Image.Image:
    width, height = card_size
    card = Image.new("RGB", card_size, "white")
    draw = ImageDraw.Draw(card)
    draw.rounded_rectangle((0, 0, width - 1, height - 1), radius=10, fill="white", outline=COLORS["line"], width=2)
    draw.text((14, 11), title, font=FONTS["panel"], fill=COLORS["navy"])
    draw.rounded_rectangle((width - 70, 11, width - 16, 36), radius=7, fill=badge_color)
    draw.text((width - 58, 16), visit_label, font=FONTS["visit"], fill="white")

    fig = plt.figure(figsize=(width / 150, height / 150), dpi=150)
    ax = fig.add_subplot(111, projection="3d")

    if points.shape[0] > 0:
        for i, j in knn_edges(points, k=4):
            ax.plot(
                [points[i, 2], points[j, 2]],
                [points[i, 1], points[j, 1]],
                [points[i, 0], points[j, 0]],
                color="#cbd5e1",
                lw=0.45,
                alpha=0.45,
                zorder=1,
            )
        ax.scatter(
            points[:, 2],
            points[:, 1],
            points[:, 0],
            s=node_sizes(volumes_ml),
            c=np.clip(volumes_ml, 1e-4, None),
            cmap="viridis",
            norm=row_norm,
            alpha=0.96,
            linewidths=0.25,
            edgecolors="white",
            depthshade=False,
            zorder=3,
        )
        lo = points.min(axis=0)
        hi = points.max(axis=0)
        center = (lo + hi) / 2.0
        span = max(float((hi - lo).max()), 1.0) * 0.67
        lo = center - span
        hi = center + span
        ax.set_xlim(lo[2], hi[2])
        ax.set_ylim(lo[1], hi[1])
        ax.set_zlim(lo[0], hi[0])

    ax.set_box_aspect((1, 1, 1))
    ax.view_init(elev=23, azim=-52)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_zticks([])
    ax.grid(False)
    for axis in [ax.xaxis, ax.yaxis, ax.zaxis]:
        axis.pane.set_alpha(0.0)
        axis.line.set_alpha(0.13)
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")
    fig.subplots_adjust(0, 0, 1, 1)
    graph_img = fig_to_image(fig)
    plt.close(fig)

    graph_img.thumbnail((width - 12, height - 45), Image.Resampling.LANCZOS)
    card.paste(graph_img, ((width - graph_img.width) // 2, 39 + (height - 48 - graph_img.height) // 2))
    return card


def histogram_card(
    *,
    patient_id: str,
    per_patient: pd.DataFrame,
    samples: pd.DataFrame,
    card_size: tuple[int, int] = (270, 220),
) -> Image.Image:
    width, height = card_size
    row = per_patient[
        per_patient["patient_id"].eq(patient_id)
        & per_patient["start_visit"].eq("T0")
        & per_patient["predicted_visit"].eq("T3")
    ].iloc[0]
    draws = samples[
        samples["patient_id"].eq(patient_id)
        & samples["start_visit"].eq("T0")
        & samples["predicted_visit"].eq("T3")
    ]["ftv_sample_ml"].to_numpy(float)

    x_max = max(float(row["ftv_raw_p95_ml"]) * 1.22, float(row["obs_ftv_ml"]) * 1.35, float(row["pred_ftv_det_ml"]) * 1.35, 5.0)
    draws_clip = draws[(draws >= 0) & (draws <= x_max)]

    card = Image.new("RGB", card_size, "white")
    draw = ImageDraw.Draw(card)
    draw.rounded_rectangle((0, 0, width - 1, height - 1), radius=10, fill="white", outline=COLORS["line"], width=2)
    draw.text((14, 11), "FTV distribution", font=FONTS["panel"], fill=COLORS["navy"])
    draw.rounded_rectangle((width - 58, 11, width - 16, 36), radius=7, fill=COLORS["blue"])
    draw.text((width - 44, 16), "T3", font=FONTS["visit"], fill="white")

    # Put the statistics in a left rail so they cannot overlap the histogram.
    draw.text((14, 54), "MC draws", font=FONTS["small"], fill=COLORS["navy"])
    draw.text((14, 76), f"mean\n{row['ftv_mc_mean_ml']:.1f} mL", font=FONTS["small"], fill=COLORS["muted"])
    draw.text((14, 118), f"SD\n{row['ftv_mc_std_ml']:.1f} mL", font=FONTS["small"], fill=COLORS["muted"])
    draw.text((14, 160), f"90%\n{row['ftv_raw_p05_ml']:.1f}-{row['ftv_raw_p95_ml']:.1f}", font=FONTS["small"], fill=COLORS["muted"])

    fig, ax = plt.subplots(figsize=(1.35, 1.25), dpi=160)
    bins = min(24, max(10, int(np.sqrt(len(draws_clip)))))
    ax.hist(draws_clip, bins=bins, color="#bfdbfe", edgecolor="#60a5fa", linewidth=0.65, density=True)
    ax.axvspan(float(row["ftv_raw_p05_ml"]), float(row["ftv_raw_p95_ml"]), color="#93c5fd", alpha=0.24, lw=0)
    ax.axvline(float(row["pred_ftv_det_ml"]), color=COLORS["blue"], lw=1.9)
    ax.axvline(float(row["obs_ftv_ml"]), color=COLORS["green"], lw=1.9)
    ax.set_xlim(0, x_max)
    ax.set_yticks([])
    ax.set_xlabel("FTV (mL)", fontsize=7, labelpad=1)
    ax.tick_params(axis="x", labelsize=7, pad=1)
    ax.spines[["top", "right", "left"]].set_visible(False)
    ax.spines["bottom"].set_color("#94a3b8")
    ax.grid(axis="x", color="#e2e8f0", linewidth=0.6)
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")
    fig.tight_layout(pad=0.1)
    hist_img = fig_to_image(fig)
    plt.close(fig)
    card.paste(hist_img, (92, 62))
    return card


def selected_alive_mask(alive_prob: np.ndarray, alive_mass: float) -> np.ndarray:
    alive_prob = np.asarray(alive_prob, dtype=float).reshape(-1)
    k = int(np.clip(round(float(alive_mass)), 0, alive_prob.shape[0]))
    mask = np.zeros_like(alive_prob, dtype=bool)
    if k > 0:
        mask[np.argsort(alive_prob)[-k:]] = True
    return mask


def rollout_prediction(
    *,
    checkpoint: Path,
    graph: dict,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    model, mean, std = lib.load_model(checkpoint)
    steps = lib.rollout_from_visit(model, mean, std, graph, start_visit=0)
    t3 = next(step for step in steps if str(step["visit_name"]) == "T3")
    return (
        np.asarray(t3["pos_pred"], dtype=float),
        np.asarray(t3["x_pred"], dtype=float),
        np.asarray(t3["alive_prob"], dtype=float).reshape(-1),
    )


def observed_graph(graph: dict, visit: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    visit_idx = VISIT_TO_IDX[visit]
    offsets = graph["visit_offsets"].tolist()
    sl = slice(int(offsets[visit_idx]), int(offsets[visit_idx + 1]))
    pos = graph["pos"][sl].detach().cpu().numpy().astype(float)
    x = graph["x"][sl].detach().cpu().numpy().astype(float)
    alive = graph["alive"][sl].detach().cpu().numpy().astype(bool)
    return pos, x, alive


def checkpoint_for_patient(runs_root: Path, fold: int) -> Path:
    ckpt = runs_root / f"fold{fold}" / "best.pt"
    if not ckpt.is_file():
        raise FileNotFoundError(
            f"Missing Endpoint+Active checkpoint for fold {fold}: {ckpt}\n"
            "Check models/bio_ftv020_alive005 or pass --runs-root explicitly."
        )
    return ckpt


def make_figure(args: argparse.Namespace) -> None:
    det = pd.read_csv(args.det_table)
    det = det[det["tag"].eq(args.model_tag)].set_index("patient_id")
    per_patient = pd.read_parquet(args.mc_root / "conditional_mc_per_patient.parquet")
    samples = pd.read_parquet(args.mc_root / "conditional_mc_samples.parquet")

    canvas = Image.new("RGB", (1720, 655), "#f8fafc")
    draw = ImageDraw.Draw(canvas)
    draw.text((34, 20), "Two held-out supervoxel graph forecasts from the Endpoint+Active model", font=FONTS["title"], fill=COLORS["navy"])
    draw.text(
        (36, 57),
        "Graph panels show the supervoxel rollout in patient-centered millimeter coordinates; histograms show T0-to-T3 MC FTV draws.",
        font=FONTS["subtitle"],
        fill=COLORS["muted"],
    )

    panel_w, panel_h = 250, 220
    hist_w = 270
    metric_w = 312
    row_h = 252
    start_y = 94
    label_x = 34
    x_positions = [226, 494, 762, 1050]
    metric_x = 1358

    for ridx, patient_id in enumerate(args.patients):
        y = start_y + ridx * row_h
        if ridx > 0:
            draw.line((34, y - 14, 1686, y - 14), fill=COLORS["line"], width=1)

        row_det = det.loc[patient_id]
        row_mc = per_patient[
            per_patient["patient_id"].eq(patient_id)
            & per_patient["start_visit"].eq("T0")
            & per_patient["predicted_visit"].eq("T3")
        ].iloc[0]
        graph = torch.load(args.graphs_root / f"{patient_id}.pt", map_location="cpu", weights_only=False)
        ckpt = checkpoint_for_patient(args.runs_root, int(row_mc["fold"]))
        pred_pos, pred_x, alive_prob = rollout_prediction(checkpoint=ckpt, graph=graph)

        t0_pos, t0_x, t0_alive = observed_graph(graph, "T0")
        t3_pos, t3_x, t3_alive = observed_graph(graph, "T3")
        pred_alive = selected_alive_mask(alive_prob, float(row_mc["alive_mass_det"]))

        t0_vol = np.clip(t0_x[:, VOLUME_IDX], 0.0, None)
        pred_vol = np.clip(pred_x[:, VOLUME_IDX], 0.0, None)
        t3_vol = np.clip(t3_x[:, VOLUME_IDX], 0.0, None)
        all_vol = np.concatenate([t0_vol[t0_alive], pred_vol[pred_alive], t3_vol[t3_alive]])
        vmin = max(float(np.nanpercentile(all_vol, 5)), 1e-4)
        vmax = max(float(np.nanpercentile(all_vol, 98)), vmin * 1.5)
        row_norm = LogNorm(vmin=vmin, vmax=vmax)

        draw.text((label_x, y + 82), patient_id, font=FONTS["row"], fill=COLORS["navy"])
        draw.text((label_x, y + 110), "held-out case", font=FONTS["subtitle"], fill=COLORS["muted"])

        cards = [
            graph_card(
                title="Observed input",
                visit_label="T0",
                points=t0_pos[t0_alive],
                volumes_ml=t0_vol[t0_alive],
                row_norm=row_norm,
                card_size=(panel_w, panel_h),
                badge_color=COLORS["slate"],
            ),
            graph_card(
                title="Predicted graph",
                visit_label="T3",
                points=pred_pos[pred_alive],
                volumes_ml=pred_vol[pred_alive],
                row_norm=row_norm,
                card_size=(panel_w, panel_h),
                badge_color=COLORS["blue"],
            ),
            histogram_card(patient_id=patient_id, per_patient=per_patient, samples=samples, card_size=(hist_w, panel_h)),
            graph_card(
                title="Observed target",
                visit_label="T3",
                points=t3_pos[t3_alive],
                volumes_ml=t3_vol[t3_alive],
                row_norm=row_norm,
                card_size=(panel_w, panel_h),
                badge_color=COLORS["green"],
            ),
        ]
        for x, card in zip(x_positions, cards):
            canvas.paste(card, (x, y))

        draw.rounded_rectangle((metric_x, y, metric_x + metric_w, y + panel_h), radius=10, fill="white", outline=COLORS["line"], width=2)
        draw.text((metric_x + 18, y + 12), "T3 forecast accuracy", font=FONTS["panel"], fill=COLORS["navy"])
        items = [
            ("Predicted FTV", f"{float(row_det['pred_ftv_ml']):.2f} mL", COLORS["blue"]),
            ("Observed FTV", f"{float(row_det['obs_ftv_ml']):.2f} mL", COLORS["green"]),
            ("FTV error", f"{float(row_det['ftv_abs_err_ml']):.2f} mL", COLORS["red"]),
            ("SWD / Chamfer", f"{float(row_det['swd_mm']):.2f} / {float(row_det['chamfer_mm']):.2f} mm", COLORS["purple"]),
            ("Alive-count error", f"{float(row_det['alive_count_abs_err']):.0f} supervoxels", COLORS["teal"]),
        ]
        iy = y + 50
        for label, value, color in items:
            draw.text((metric_x + 18, iy), label, font=FONTS["small"], fill=COLORS["muted"])
            draw.text((metric_x + 150, iy - 2), value, font=FONTS["metric"], fill=color)
            iy += 30

    legend_y = 592
    draw.line((34, legend_y, 1686, legend_y), fill=COLORS["line"], width=1)
    draw.text((36, legend_y + 15), "Legend:", font=FONTS["legend"], fill=COLORS["navy"])
    draw.text((92, legend_y + 15), "nodes: low", font=FONTS["legend"], fill=COLORS["muted"])
    draw_viridis_scale(draw, 170, legend_y + 18)
    draw.text((274, legend_y + 15), "high supervoxel FTV contribution; larger node = larger local volume; gray edges = kNN graph;", font=FONTS["legend"], fill=COLORS["muted"])
    draw.rectangle((894, legend_y + 18, 914, legend_y + 28), fill="#bfdbfe", outline="#60a5fa")
    draw.text((922, legend_y + 15), "bars = MC draws; shaded band = raw 90%;", font=FONTS["legend"], fill=COLORS["muted"])
    draw.line((1222, legend_y + 16, 1222, legend_y + 31), fill=COLORS["blue"], width=3)
    draw.text((1232, legend_y + 15), "blue = deterministic prediction;", font=FONTS["legend"], fill=COLORS["muted"])
    draw.line((1454, legend_y + 16, 1454, legend_y + 31), fill=COLORS["green"], width=3)
    draw.text((1464, legend_y + 15), "green = observed FTV.", font=FONTS["legend"], fill=COLORS["muted"])

    for out in args.outputs:
        out.parent.mkdir(parents=True, exist_ok=True)
        canvas.save(out, quality=95)
        print(out)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--graphs-root", type=Path, default=ROOT / "data/ispy2/graphs_consistent")
    ap.add_argument("--runs-root", type=Path, default=ROOT / "models/bio_ftv020_alive005")
    ap.add_argument("--mc-root", type=Path, default=ROOT / "results/conditional_mc_bio_retrained/bio_ftv020_alive005")
    ap.add_argument(
        "--det-table",
        type=Path,
        default=ROOT / "results/consistent_forecaster_v2_bio_eval/notebook_exports/bio_vs_baseline_t3_per_patient.csv",
    )
    ap.add_argument("--model-tag", default="bio_ftv020_alive005")
    ap.add_argument("--patients", nargs="+", default=["ISPY2-209397", "ISPY2-149654"])
    ap.add_argument(
        "--outputs",
        type=Path,
        nargs="+",
        default=[
            ROOT / "paper/figures/ispy2_two_patient_rollout_static.png",
        ],
    )
    return ap.parse_args()


if __name__ == "__main__":
    make_figure(parse_args())
